### ISSUE TITLE
Shiny Client Errors: Cannot read properties of null (reading 'deps')

### ISSUE THREAD

**Issue by pawelru** [posit-dev/r-shinylive#128] opened 2024-09-03 07:44 UTC
https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKcqajGIgEwCu1OAGcMAcwpxm1AJQAdCHSYsOo1CwDWdCHEUQlaVAAIAPAFoTtCLVLslJk-yikoJgLwmu1APou3dgBJLCCAZU9rRlpROVxHEz4hEVFIpOExBwgnJ1IYXwA3FlooehFfJiIAd1EZBzAANWLSkRMAIUZq2sYFMAMnAwMlUQALG1YAQXR2YwASQVpcEznugpkDMABfAF0gA

I think it's due to this change in the `htmlwidgets`: https://github.com/r-wasm/htmlwidgets/commit/892798fcbdd3788e4f24ddd0948be6e5f0a1e373

console log
```
shiny.min.js:2 TypeError: Cannot read properties of null (reading 'deps')
    at shinyBinding.renderValue (htmlwidgets.js:515:44)
    at e.<anonymous> (shiny.min.js:2:174316)
    at m (shiny.min.js:2:166780)
    at Generator.<anonymous> (shiny.min.js:2:168103)
    at Generator.next (shiny.min.js:2:167139)
    at R_ (shiny.min.js:2:172750)
    at s (shiny.min.js:2:172948)
    at shiny.min.js:2:173009
    at new Promise (<anonymous>)
    at e.<anonymous> (shiny.min.js:2:172889)
```

When I enter the JS debugger I can see the following:
![image](https://github.com/user-attachments/assets/6c2be701-c288-4efa-88d7-1fe385a922a8)
`data` is `null` thus `data.deps` throws

Outside of shinylive everything is fine. Entering debugger in the same place does not show null value.

I'm trying to create a base shiny example for this to debug this easier but the example above shows that it is possible to have null value there so it would make sense to handle this somehow.

I have seen https://github.com/posit-dev/r-shinylive/issues/124 but adding loading dependency from external CDS does not help.

**Comment by pawelru** [comment] 2024-09-03 09:56
similar issue: https://github.com/r-wasm/webr/issues/330

**Comment by pawelru** [comment] 2024-09-03 11:46
Minimal reprex

https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4aIbM27ACIAVWSICutAAQAeALTbUUAOZwA+p1oATOPRbsR27Vdv3G2gLwubdh0+dtAm44AgBreiIADwBJCFQNUkcIQMC+BNIY6y9tITBGOABHPNwA1OooejhqHLyCwu0ANyhqDTgSssDm1rgcgDEAQQAZAGUAUU7ZZwFSlO1VAHlEjPYiZcSs2rBrWk5SAAVqIlI82XUITjhGRqu9QwAzDQgCUloSdnTE3G010gyBbQgAK-DIAEh2e0Oxzu2gKEFsjFU7CBc2c9Q+8USoPqUzSjF2AQAvrJCSIRDw+KwBuh2FoclpvpdrrdvEyboxZGBCQBdIA

**Comment by georgestagg** [comment] 2024-09-06 08:21
I believe I have tracked down the underlying issue. That is, I now know how and why the problematic `null` object is being generated.

The issue is related to the patches made to webR's distribution of Shiny so that it can work well under WebAssembly. I have fixed the problem and made a new release of the package at https://github.com/r-wasm/shiny/releases.

With this latest build, the example app works without generating any errors:
![Screenshot 2024-09-06 at 09 17 20](https://github.com/user-attachments/assets/9dfa334e-dc9a-427e-8f86-654e601ff162)

Shinylive won't automatically pick up the change, but I will include upgrading the Shiny R package as part of some other work I am currently undertaking. Once that work has all been merged, it should fix the issue on shinylive.io etc.

**Comment by georgestagg** [comment] 2024-09-26 15:53
The above reprex ([here](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4aIbM27ACIAVWSICutAAQAeALTbUUAOZwA+p1oATOPRbsR27Vdv3G2gLwubdh0+dtAm44AgBreiIADwBJCFQNUkcIQMC+BNIY6y9tITBGOABHPNwA1OooejhqHLyCwu0ANyhqDTgSssDm1rgcgDEAQQAZAGUAUU7ZZwFSlO1VAHlEjPYiZcSs2rAovNl1CE44RkajvUMAMw0IAlJaEnZ0xNxtNdIMgW0QANeMgBIos7aAoQWyMVTsL5zZz1B7xRK-epTNKMWicAIAX1k6JEIh4fFYA3Q7C0OS0z0Ox1O3gpJ0YsjA6IAukA)) should now run successfully without errors on shinylive.io when toggling the `req()` switch.

The associated PR for the R Shinylive package to include the latest version of the assets is here: https://github.com/posit-dev/r-shinylive/pull/131

**Comment by georgestagg** [comment] 2024-10-09 10:32
Yes, I think the raising of the `TypeError: Cannot read properties of null (reading 'deps')` error means that this is almost certainly the same underlying problem. The issue is not with htmlwidgets itself, it is just very easy to trigger using widgets. It seems another way to trigger the bug was by using `req()`.

The underlying issue was in my Wasm patches to R Shiny so that it can run in Shinylive. The patches did not correctly raise conditions to be handled, instead internally returning a `NULL` where an R condition should be raised. This filtered out to the application and caused the "`Cannot read properties of null`" error in the JavaScript side of things.

It should now be fixed on https://shinylive.io/r/examples/, and once https://github.com/posit-dev/r-shinylive/pull/131 is merged also in the outputs of the R Shinylive package and Quarto documents.

**Closed** 2024-10-15 12:56 UTC
